### ISSUE TITLE
Switch from Atlas Google Analytics Key

### ISSUE THREAD

**Issue by stdavis** [agrc/health-facilities#10]
Hey @keatonwalker:

Looks like the Google Analytics key for this project was never changed from the Atlas one. I probably forgot to tell you that this needs to happen when you make a copy of Atlas.

You'll need to create a new property under the agrc Google Analytics account for this project and update the key. I'd be happy to help walk you through this.

**Comment by keatonwalker** [comment]
Thanks for noticing @stdavis. I have a new analytics code for health facilities and I replaced the Atlas one. Would you mind checking our Google Analytics to see if I created the new property correctly?

**Comment by stdavis** [comment]
Looks good to me. I can see data coming in on the new property and it falling off on atlas. 👍
