### ISSUE TITLE
choose production dns

### ISSUE THREAD

**Issue by steveoh** [agrc/health-facilities#13]
pick a dns for the production url

**Comment by nathankota** [comment]
(Another app that's new to me! Locating a client contact for it.)

**Comment by nathankota** [comment]
Going along with the theme of keeping dev and prod DNSs as similar as possible, I will request health-facilities.ugrc.utah.gov

**Comment by nathankota** [comment]
INC1493876

**Comment by steveoh** [comment]
Please have the cloud machine add the new dns to the `ut-dts-agrc-health-facil-prod` project

**Comment by nathankota** [comment]
INC1495518  (I will be sure to close it this time when the INC is resolved)

**Comment by nathankota** [comment]
This task is complete, but I must not have proper credentials in this repo to close the issue. I can only submit a comment.
